### ISSUE TITLE
Change database structure to save surveys in individual collections

### ISSUE THREAD

**Issue by empicano** [fastsurvey/backend#31]

**Comment by dostuffthatmatters** [comment]
Great idea! Think about that for every collection we need a "cursor object" for querying that particular collection.

We have to consider the possible memory use/connection count overhead since ever cursor may need a connection to the the cluster and there is a limit on connection for a cluster. For the M2 cluster i thinks its 500 simultanous connections.

If that does not seem to be an issue, awesome :) But if it is then we might find a way to group surveys into different collections without having one collection per survey. 

However the one collection per survey approach seems the most elegant one! And maybe the connection count is referring to the "database cursor object" :D

**Comment by empicano** [comment]
Thanks for the hint to the connection counts, didn't realize that could be an issue. As far as I know, as a connection counts the connection between one client (distinguished by its IP address) and the database. Thus, no matter the number of collections and cursors, the connection count should stay at one since we're only querying from our server. Correct me if I'm wrong here though, please.

I'm currently still mulling over the data model design, especially as we want to integrate users in the future. So, the one collection per survey schema is not set in stone yet anyways -- but I'm pretty sure that we can't scale well while putting the entries for all surveys in the same giant collection :smile: Have to read up on this still before I can make a decision!

**Comment by dostuffthatmatters** [comment]
One thing that will probably help with large collections: Custom indexes.

You can speed up queries on large collections by using more than just the document id's as indexes, but custom indexes -> https://docs.mongodb.com/manual/indexes/

If we use the survey identifier `username/survey-name` as an index then with queries not each document has to be scanned for its survey identifier but this step of reducing results has already been done by the db design.

Still, one large collection for every survey in existence would be way too large, but maybe some mix would do it :)

I'd love to do some experiments on that! 😊

**Comment by empicano** [comment]
Good hint! Going with indexes would certainly improve performance when we're saving everything in one collection. One use case where indexes shine, as described in the [MongoDB documentation on indexes](https://docs.mongodb.com/manual/indexes/) is when querying for subsets of a collection that is sortable based on the index field, especially if the read/write ratio is big, and the queried subsets cannot be known in advance (e.g. for timeseries data, if one time I want all the data for one day, another time for a one year or from 8am to 3pm the next day).

Our data is actually simpler than that. Why we can use multiple collections instead of indexing is because our queries over submissions only need categorical data (admin name, survey id, submission id), and the queries over submissions are known in advance:
- create/replace single submissions
- get all submissions from a survey (to process them into results)
- delete all submissions from a survey

The main thing that we want, is to (1) dump submission data _fast_ into the database. This is the operation that will be performed the most, thus it is the one that we have to optimise. I don't actually care much about minimizing the time that the processing of the submissions of a finished survey takes (2), as it's done only once per survey.

For (2), both indexing and and multiple collections would be equally fast. But for (1) indexing takes longer than using multiple collections. Building the index takes time and disk space, and it has to be altered for every document that's inserted. This index building is worth it for a big read/write ratio, in our case, we only have a single read that wouldn't work using just primary keys, namely (2). 

There's also an [interesting section in the docs](https://docs.mongodb.com/manual/core/data-model-operations/#large-number-of-collections) on this subject of using multiple collections.

I'm against a mix of the two options. As far as I know MongoDB once had limits for the number of collections, but doesn't have them anymore, so there's nothing in the way of having lots of collections.
