### ISSUE TITLE
Add CORS policy

### ISSUE THREAD

**Issue by dostuffthatmatters** [fastsurvey/backend#44]
`Access to XMLHttpRequest at 'https://backend.dev.fastsurvey.io/users/mumbojambo' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Solution: https://fastapi.tiangolo.com/tutorial/cors/

**Comment by empicano** [comment]
If I understand it correctly this should do right? Or do we need other origins (e.g. http)?
I'll read into this a little more to understand what this does 😄

**Comment by dostuffthatmatters** [comment]
I'll just allow any origin. That's easier to manage ☺️
