### ISSUE TITLE
API: Create new survey - duplication of survey_name

### ISSUE THREAD

**Issue by dostuffthatmatters** [fastsurvey/backend#48]
Very small thing 😅

For `POST /users/{username}/surveys/{survey_name}` (creating a new survey) the username has to be only in the path but the survey_name has to both in the path and the posted config.

It's just a little bit confusing - my thoughts: Either both in path **and** config or neither.

**Comment by empicano** [comment]
You can change the name of a survey by using different survey names in path and body via `PUT /users/{username}/surveys/{survey_name}`. For the `POST` request this is not strictly necessary (and will fail), you're right, but I like the consistency.

**Comment by dostuffthatmatters** [comment]
Aah, that makes sense! Thanks :)

So with a new survey_name use the old one in the path and the new one in the config right?

**Comment by empicano** [comment]
Yes, that's it!
