### ISSUE TITLE
It is possible to create a survey (in published mode) without any fields.

### ISSUE THREAD

**Issue by dostuffthatmatters** [fastsurvey/backend#50]
The following is a valid configuration: 
```
{
    "survey_name": "badum",
    "title": "Email Test",
    "description": "",
    "start": 1621712880,
    "end": 1653248880,
    "draft": false,
    "authentication": "open",
    "limit": 0,
    "fields": []
}
```

Maybe it is just a feature to allow an empty fields list in the `draft: false` state :)

Running on `0466523 (HEAD -> master, origin/master, origin/HEAD) Set access token expiry to one week`.

**Comment by empicano** [comment]
Fixed with 1ed8ee550fc56e3ac927079ffc2165002893823d. Configurations are validated by the same rules, whether `draft` is set to True or not.
