### ISSUE TITLE
GET `/users/{username}` returns the wrong account format

### ISSUE THREAD

**Issue by dostuffthatmatters** [fastsurvey/backend#51]
What it should return (according to the API docs):
```
{
    "email_address": "a@fastsurvey.io",
    "username": 1618530873,
    "verified": true
}
```

What it returns instead:
```
{
    "email_address": "a@fastsurvey.io",
    "creation_time": 1618530873,
    "verified": true
}
```

Running on `13f784c (HEAD -> master, origin/master, origin/HEAD) Adapt test survey result examples to updated example submissions`.

**Comment by empicano** [comment]
My initial thought was to return `email_address`, `creation_time` and `verified`. As such, it's a fault in the documentation, well spotted! Returning the username does not make much sense here or does it?

**Comment by dostuffthatmatters** [comment]
You are right, doesn't make much sense to return the username again. The documentation still has to be updated ;)

**Comment by empicano** [comment]
Done, and deployed!
