### ISSUE TITLE
Fetch config: Response from backend does not change with config in database.

### ISSUE THREAD

**Issue by dostuffthatmatters** [fastsurvey/backend#56]
I am using the current `backend.dev.fastsurvey.io` server.

I used `GET https://backend.dev.fastsurvey.io/users/dostuffthatmatters/surveys/badum` to fetch a config. After that I modified the description in the console (in the database it has also been updated).

However, the fetch-config response from the backend remains unchanged. After five minutes (server has _not_ shut down) the response is still the same. But `/users/dostuffthatmatters/surveys` (fetch all configs with authentication) works fine.

Both `testing` and `production` don't have the `dostuffthatmatters` account so I am sure that all of this is using the same database.

**Comment by dostuffthatmatters** [comment]
Same thing for a new survey I created. The first version of the config (template from creation) will be returned.

**Comment by dostuffthatmatters** [comment]
After the server has shut down once the new version was returned.

**Comment by empicano** [comment]
This is related to #49, will fix that soon, sorry for the wait! Due to the error thrown the survey cache is not updated, when you restart the server, the survey is loaded freshly from the database again, that's why it works afterwards.

**Comment by dostuffthatmatters** [comment]
No worries :) I have enough stuff to do left 😅

**Comment by dostuffthatmatters** [comment]
![](https://i.giphy.com/media/DUtVdGeIU8lmo/giphy.webp)

**Comment by empicano** [comment]
![giphy](https://user-images.githubusercontent.com/26978146/117217980-9e10c980-ae02-11eb-8227-f3121e59a65d.gif)
