### ISSUE TITLE
Verification email is broken

### ISSUE THREAD

**Issue by dostuffthatmatters** [fastsurvey/backend#57]
Upon my submission (which itself was successful), I received the following email:
```
Hi there, we received your submission!

Survey: We need more surveys!

Please verify your submission by [dev.fastsurvey.io/dostuffthatmatters/hello-fellow-humans/verification/a5de09b4b54576f089f5325742fb160f2487ed92ae7dfb4ed52d45f1db6bed5a24be3e6c3159811045ae5f2a3dbbaccb2c23827629587828ca85e50e53cdae55]clicking here.

Best, the FastSurvey team
```

So, the link has to be fixed. And it has to point to the correct backend (backend.dev.fastsurvey.io) :)

In addition to that it ended up in the spam folder, I think because of the email sender:
`noreply=fastsurvey.io@email.fastsurvey.io im Auftrag von FastSurvey <noreply@fastsurvey.io>`

**Comment by dostuffthatmatters** [comment]
When I try to use this link with backend.dev... in front I get a 404 response.

Additionally, is there any chance we could get this confirmation any shorter? :) Maybe 64 characters instead of 128?

**Comment by dostuffthatmatters** [comment]
Ok I looked up the new path format in the verification:

https://backend.dev.fastsurvey.io/users/dostuffthatmatters/surveys/hello-fellow-humans/verification/a5de09b4b54576f089f5325742fb160f2487ed92ae7dfb4ed52d45f1db6bed5a24be3e6c3159811045ae5f2a3dbbaccb2c23827629587828ca85e50e53cdae55

The backend.dev responds with a 422 and the following message:
```
{
  "detail": [
    {
      "loc": [
        "path",
        "verification_token"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    }
  ]
}
```

**Comment by empicano** [comment]
Hm, weird, it should be displayed a link, but not the whole URL, I'll check on that again. But you're right on the URL, I mixed that up.

The email address is as expected, we're sending from `email.fastsurvey.io` not `fastsurvey.io`. Using subdomains for email sending seems to be best practice, you can read up on that if you're interested e.g. [here](https://help.mailgun.com/hc/en-us/articles/202256730-How-do-I-pick-a-domain-name-for-my-Mailgun-account). Why it's classified as spam I don't know, but at this time there's nothing I can do about that. Domain and IP reputation is built up over time, when we're sending more emails and those emails are well engaged with that should become better.

What do you mean by making the confirmation shorter? If you mean the verification token, no, sorry. The secrets module documentation states that [as of 2015, it is believed that 32 bytes (256 bits) of randomness is sufficient for the typical use-case](https://docs.python.org/3/library/secrets.html#how-many-bytes-should-tokens-use), that was six years ago, so I'm doubling that to 64 bytes (128 characters).

I don't understand the 422 though, gotta investigate 😄
